export default function InfoLocais() {
    const fumaca = 'O visual da Cachoeira da Fumaça está entre os mais belos cenários da Chapada Diamantina. São, aproximadamente, 340 metros de queda d’água cercada por espetaculares paredões rochosos que formam um cenário mágico em meio à natureza exuberante do Vale do Capão. Difícil não se emocionar ao chegar ao topo dessa cachoeira, considerada uma das maiores do Brasil. Ao todo, são 12 km de trilha, ida e volta, sendo que a subida inicial, com 2 km, exige muito fôlego e preparo físico dos visitantes. Ultrapassada a etapa inicial, o restante do trajeto é bem mais fácil e agradável. Ainda que seja uma trilha de nível médio, o visual da Cachoeira da Fumaça ao final compensa todo o esforço!'
    const riachinho = 'A visita à Cachoeira do Riachinho está quase sempre associada à da Cachoeira da Fumaça. As duas estão muito próximas e, como não há oportunidade para banho na visita à Cachoeira da Fumaça por cima, o negócio é aplacar o cansaço e o calor em outra queda d’água. E a melhor opção nos arredores é a Cachoeira do Riachinho. O lugar tem acesso muito fácil e não será necessário gastar energia para chegar ao belo poço de água. Por lá, a pedida é mesmo só relaxar. Ótima opção depois dos 12 km de trilha da Cachoeira da Fumaça. A Cachoeira do Riachinho tem um poço bem grande para banho e dá até para chegar pertinho do paredão e tomar banho direito na queda d’água. O visual para o Vale do Capão é lindo e, ao final do dia, quando é mais comum que os turistas cheguem, ainda dá pra curtir o pôr do sol deitado nas pedras ou dentro da água. '
    const grutaLapa = 'Parte de um sistema de 42 km de cavernas, a Gruta da Lapa Doce é uma visita extraordinária para os fãs das belezas subterrâneas. Atualmente apenas 850 metros desse paraíso está aberto à visitação, mas a beleza ocupa cada pedacinho do lugar. A visita à Gruta da Lapa Doce começa com uma descida íngreme por trilha e escadas. O trajeto não é difícil e pode ser percorrido por qualquer visitante sem dificuldade de locomoção. Depois de dez minutos de caminhada, os turistas chegam à boca da gruta e passam a andar no interior em busca das maravilhosas formações de espeleotemas, estalactites e estalagmites. Tudo com lanternas individuais para que cada visitante observe as belezas no tempo que desejar.'
    const lencois = 'Principal base para quem embarca rumo à Chapada Diamantina, Lençóis é um ótimo ponto de apoio para realizar diversos passeios. Além de sediar muitas agências de turismo, a cidade oferece também um boa variedade de pousadas e restaurantes deliciosos! Aliás, a culinária é ponto forte do lugar, que tem cardápios bem elaborados. Lençóis tem casas de fachadas coloridas e ruas de pedra, muitas delas destinadas apenas aos pedestres, às mesinhas dos lindos restaurantes e aos músicos de altíssima qualidade que encantam e entretêm os viajantes. Lençóis também oferece um bom comércio e por isso é recomendada a quem não abre mão de infraestrutura durante a viagem. Todos os principais passeios oferecidos na Chapada Diamantina podem ser feitos a partir de Lençóis, o que facilita muito a vida do turista.'
    const morroInacio = 'A imponente imagem do Morro do Pai Inácio toma conta do cenário da Chapada Diamantina. Do alto, é possível apreciar a imensidão e beleza da região. Um dos passeios mais procurados de toda a Chapada, o Pai Inácio é visita imperdível, especialmente ao pôr do sol, quando o tom de dourado da luz dá belos contornos às rochas e torna tudo ainda mais impressionante. A subida do Morro do Pai Inácio não é das mais difíceis, mas exige um pouco de fôlego e disposição para transpor os 500 metros da trilha que leva ao topo. Ao andar pelas pedras no topo do Pai Inácio, não deixe de reparar nas formas desenhadas pela água entre as rochas. Com sorte (e algumas dicas do guia) você encontrará o coração que é símbolo desse lugar. Uma linda locação para aquele retrato romântico.'
    const valeCapao = 'O Vale do Capão — que tem nome oficial de Caeté Açu — é quase mítico entre os viajantes mais descolados e alternativos na Chapada Diamantina. O pequeno vilarejo, incrustado em meio à exuberante natureza da Chapada Diamantina e com ares esotéricos, atrai os turistas que desejam contato direto com as belezas da região. O lugar é pequeno e formado basicamente por uma rua principal e uma praça, onde estão as agências e restaurantes locais. A graça por lá está nas pessoas que se hospedam na região, nas deliciosas pousadas em meio à natureza e nas maravilhosas atrações da Chapada Diamantina que têm o Vale do Capão como base de partida.'
    
    return { fumaca, riachinho, grutaLapa, lencois, morroInacio, valeCapao }
}